---
title: "Evaluación de Sistemas de Vigilancia: Métricas de Rendimiento"
author: "IDASH"
format:
  pdf:
    include-in-header:
      - header.tex
    include-before-body:
      - before-body.tex
    toc: true
    toc-title: "Tabla de Contenidos"
    number-sections: true
    number-depth: 3
    lot: true
    lof: true
    documentclass: scrreprt
    fig-pos: "H"

crossref:
  lot-title: "Lista de Tablas"
  lof-title: "Lista de Figuras"
  tbl-title: Tabla
  fig-title: Figura

execute:
  echo: true
  warning: false
  error: false

---

# Conjunto de datos

## Librerías
```{r}
pacman::p_load(tidyverse, dlookr,inspectdf,skimr)

```


```{r}


deaths <- read_csv(
  "data/deaths.csv.gz",
  col_types = cols(
    fecha_fallecimiento = col_date(format = "%Y-%m-%d"),
    edad_declarada = col_integer(),
    sexo = col_character(),
    clasificacion_def = col_character(),
    departamento = col_factor(),
    provincia = col_factor(),
    distrito = col_factor(),
    uuid = col_factor(),
    age_group = col_factor()
  )
)

hospital <- read_csv(
  "data/hospital.csv.gz",
  col_types = cols(
    eess_renaes = col_factor(),
    eess_diresa = col_factor(),
    eess_red = col_factor(),
    eess_nombre = col_factor(),
    id_eess = col_factor(),
    id_persona = col_character(),
    edad = col_integer(),
    sexo = col_factor(),
    fecha_ingreso_hosp = col_date(format = "%Y-%m-%d"),
    flag_uci = col_logical(),
    fecha_ingreso_uci = col_date(format = "%Y-%m-%d"),
    fecha_ingreso_ucin = col_date(format = "%Y-%m-%d"),
    con_oxigeno = col_logical(),
    con_ventilacion = col_logical(),
    fecha_segumiento_hosp_ultimo = col_date(format = "%Y-%m-%d"),
    evolucion_hosp_ultimo = col_factor(),
    flag_vacuna = col_integer(),
    fecha_dosis1 = col_date(format = "%Y-%m-%d"),
    fabricante_dosis1 = col_factor(),
    fecha_dosis2 = col_date(format = "%Y-%m-%d"),
    fabricante_dosis2 = col_factor(),
    fecha_dosis3 = col_date(format = "%Y-%m-%d"),
    fabricante_dosis3 = col_factor(),
    cdc_positividad = col_logical(),
    cdc_fecha_fallecido_covid = col_date("%d/%m/%Y"),
    cdc_fallecido_covid = col_logical(),
    ubigeo_inei_domicilio = col_factor(),
    dep_domicilio = col_factor(),
    prov_domicilio = col_factor(),
    dist_domicilio = col_factor(),
    missing = col_logical()
  )
)
```

# Análisis completitud datos muertes COVID

```{r}

tr_na_muerte<- inspect_na(deaths)
tr_na_hosp<-inspect_na(hospital)


```


# Análisis completitud datos hospitalizaciones COVID

```{r}

tr_na_hosp<-inspect_na(hospital)

tr_na_hosp
```



